Add content to media and publications
UncountedDeaths/UncountedDeaths.github.io pull request #29
Opened 2022-04-05 05:10 UTC by toucham

**Changes:**
- add static content to media and publications page

**Notes:**
- Not sure what image to use for publications (there are image in `<meta />`, will probably use that to represent each publication)
- We could use `<meta />` elements in the media to extract information (image, title, description, date) which could be done automatically through page scraper lib however we don't have a backend yet so everything is done manual

2022-04-05 19:55 UTC, IanSaucy commented
One possible option for auto-scraping would be to use a serverless function. Out of scope for this week but possible after the launch on friday.

2022-04-05 19:57 UTC, IanSaucy requested changes
Could you make the image boxes a fixed size and just crop images that don't fit? This happened on the Publication page with the different sized images. I also think we might want to pull slightly different images than those used currently. Trying to include an image that's a bit more visual maybe as is in the wireframe.

Also up for discussion, should the sizing be done in `px` or something responsive like `vh, em, rem` etc

2022-04-05 20:19 UTC, toucham commented
> Could you make the image boxes a fixed size and just crop images that don't fit? This happened on the Publication page with the different sized images. I also think we might want to pull slightly different images than those used currently. Trying to include an image that's a bit more visual maybe as is in the wireframe.
> 
> Also up for discussion, should the sizing be done in `px` or something responsive like `vh, em, rem` etc

If we're planning to make the website work on mobile, I think it is best to use either `vh, vw, rem, %`. Only use `px` in specific situation like setting `max-width`. However, I also highly suggest that we should prioritize `rem` with `media-query` over other units like `vh,vw,%` that scale according to parent elements since it's really hard to control these units to make it look good on every size of monitor.  

Furthermore, it is probably best to make most elements have [`display: flex`](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) so that the elements size will scale accordingly to the parent elements/monitor size.

2022-04-06 17:29 UTC, IanSaucy requested changes
Pending updates for responsiveness

2022-04-06 21:14 UTC, IanSaucy requested changes
Looks good, the dynamic sizing messed up the mobile menu bar text but it's not that big of a deal. Just file a bug into the backlog on Trello to fix later.

Otherwise just increasing mobile to 12px base. Looks super good, thank you!

2022-04-06 21:14 UTC, IanSaucy commented on src/styles/themes.less
> +    font-size: 10px
Can you make this 12px instead, I think 10px is a little small.

2022-04-06 21:27 UTC, IanSaucy approved these changes
lgtm

2022-04-07 03:24 UTC, merged