update Home page to v3.1
UncountedDeaths/UncountedDeaths.github.io pull request #37
Opened 2022-04-11 19:11 UTC by toucham

**Changes:**
- make navbar overlay photo
- update homepage to v3.1 of the designs

2022-04-11 19:57 UTC, IanSaucy requested changes
**Really good** work on everything. I think you just need the calc() in one part. 

Also noticed that the recent media and publications images/content should be left aligned to the title. Right now they seem to float separately from the title. I know this might cause some weird things with the mobile cutoff but that is probably fine. 

Also want to tag in @minkyoseo to give thoughts on the padding. The changes reduce the padding a bit but want to make sure it's still fine! I think the less padding is all around good but want to double check.

2022-04-11 19:57 UTC, IanSaucy commented on src/styles/ContentLayout.module.less
> +  padding: @navbar-height+3rem 9%;
I think you need to use `calc(..)` for this calculation to actually work. Probably why the padding looks a bit different right now.

2022-04-11 20:25 UTC, Ingi-Hong commented
Things I noticed: 
- CEID logo text should be white on the landing page (right now its black)
- I noticed its kind of hard to see Home navigation button when its selected, since it's that dark cyan color on a black background. Maybe @minkyoseo has some thoughts on changing the selected color? 

Awesome job :D

2022-04-11 20:26 UTC, Ingi-Hong reviewed
Things I noticed:

- CEID logo text should be white on the landing page (right now its black)
- I noticed its kind of hard to see Home navigation button when its selected, since it's that dark cyan color on a black background. Maybe @minkyoseo has some thoughts on changing the selected color?

Awesome job :D

2022-04-11 20:47 UTC, IanSaucy commented
Chiming in about the logo, since it's all a single SVG file we will need to apply a style on the SVG or have an alternative to display that's inverted. I've not looked at the SVG to see how easy it would be to selectively style just the text and or create an inverted version. 

I think we log that as a "bug" in Trello.

2022-04-12 15:13 UTC, IanSaucy approved these changes
lgtm 

Log a bug for the mobile design and how the centering should be done etc. @minkyoseo Will need to chime in for that one.

2022-04-12 15:28 UTC, merged