Add team members
UncountedDeaths/UncountedDeaths.github.io pull request #49
Opened 2022-04-25 20:57 UTC by sharlak1

added members for research, collaborators and media

2022-04-26 21:22 UTC, IanSaucy requested changes
Overall looks good! Could you swap out the placeholder image with the one attached? It's an SVG so you might need to modify the underlying component to support that. You can make the name shorter as well that the default on the file.
![person_FILL1_wght400_GRAD200_opsz48](https://user-images.githubusercontent.com/30986157/165394475-7e6d1509-2b5d-4c33-9b0a-fef3f30b2ab4.svg)

2022-04-26 21:22 UTC, IanSaucy commented on src/styles/OurTeamPage.module.less
> +  width: 70%;
Is there a reason why you added this?

2022-04-26 23:20 UTC, sharlak1 commented on src/styles/OurTeamPage.module.less
> +  width: 70%;
To fix title content responsiveness

2022-04-27 02:23 UTC, IanSaucy approved these changes
lgtm

2022-04-27 02:23 UTC, merged